[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 100_000_000_000_000

[accounts.relayer]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 100_000_000_000_000

[accounts.buyer]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragment small fit harbor leg humble erase sustain anger ring stove ozone valley laugh"
balance = 100_000_000_000_000
